### ISSUE TITLE
How to get ground truth for the dataset and evaluation procedure?

### ISSUE THREAD

**Issue by 1haomingtian** [prgumd/SalientDSO#1]
Firstly, I have run [SALGAN](https://github.com/imatge-upc/salgan) successfully，however, if I run a dataset from https://vision.in.tum.de/mono-dataset, I only predict it and no groud truth.
Secondly, there's no evaluation procedure for the results of saliency map.
Could you tell me how to get ground truth for the dataset and evaluation procedure?  Thank you very much.

**Comment by NitinJSanket** [comment]
Hi 1haomingtian,
TUMMonoVO dataset's eveluation works without a ground truth. The evaluation scripts are on the same website in Matlab. 

Hope this helps!
Nitin

**Comment by 1haomingtian** [comment]
> Hi 1haomingtian,
> TUMMonoVO dataset's eveluation works without a ground truth. The evaluation scripts are on the same website in Matlab.
> 
> Hope this helps!
> Nitin

 Thanks for your replying, could you please give me the website in Matlab because I've never seen it.

Thank you very much.

Sincerely,

1haomingtian

**Comment by NitinJSanket** [comment]
Here you go: http://vision.in.tum.de/mono/evaluation_code_v2.zip

**Comment by 1haomingtian** [comment]
Thanks a lot.

**Comment by Mickeyyyang** [comment]
hello, NitinJSanket~
I want to ask about the instructions for 5.2 and 5.3 if it will be updated?
thx!

**Comment by NitinJSanket** [comment]
Hi @xuyangbit,
I cannot find the shell script I wrote for running SalGAN and PSPNet. You can follow the instructions on their repos directly to run it on your images and save them in the format given. That should work.

**Comment by Mickeyyyang** [comment]
OK, I will try it~
thank you very much~

Nitin J. Sanket <notifications@github.com> 于2020年3月16日周一 上午2:31写道：
