### ISSUE TITLE
About "Test Semantic Filtered Saliency Setting"

### ISSUE THREAD

**Issue by Mickeyyyang** [prgumd/SalientDSO#3]
Hi, I want to ask a question about "5.3. Test Semantic Filtered Saliency Setting".
I can't solve the problem of how to predict the output to many images (a dataset) once by PSPNet.
so can you help me?
thanks ～～～

**Comment by NitinJSanket** [comment]
You can use the code from [here](https://github.com/hellochick/PSPNet-tensorflow/blob/master/inference.py) and write a shell script around it to call it on every single image.
