### ISSUE TITLE
About "CVL" dataset

### ISSUE THREAD

**Issue by Mickeyyyang** [prgumd/SalientDSO#4]
hello, do you have the ground truth of camera trajectory about the CVL datasets. I want to compare with the result of salientdso.
thank you very much~~

**Comment by NitinJSanket** [comment]
Sadly, we don't have the ground truth for the CVL-UMD dataset. You can compare trajectories on the ICL-NIUM and TUM monoVO dataset as they have ground truth and evaluation kits available.

Also, you can do a qualitative evaluation on the CVL-UMD dataset.
